### ISSUE TITLE
Slow Voltage Set up

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [caenHV/Setup#17]
Поменять RUP у каналов + поменять идеалогию выставки напряжения.
Сейчас напряжение на разных каналах выставляется с большой задержкой (заметна, чтобы всё сгорело).
Сделать выставление более или менее равнемерным (параллельным?).

**Comment by nikita-p** [comment]
Возможно наша проблема (как минимум её часть) в этом кусочке кода
https://github.com/caenHV/Setup/blob/26b9f58bcf71bccab48e6b478551fc977ff21e65/caen_setup/Setup/Handler.py#L388-L392

1. pw_up включает питание для всех каналов сразу, но само находится в цикле (т.е. вместо линейного времени мы тратим квадратичное) + возникает проблема, что Pw включается для всех каналов до того, как мы зададим верный VSet
2. метод `__set_parameters` апдейтит базу данных после каждого вызова (если мы выставляем для всех плат все каналы, то таких вызовов уже много, а при текущем расположении pw_up это число в квадрате), может тогда есть смысл вызывать его не для каждого канала отдельно, а сразу для `List[Channel_info]`?
https://github.com/caenHV/Setup/blob/26b9f58bcf71bccab48e6b478551fc977ff21e65/caen_setup/Setup/Handler.py#L362

**Возможное решение**: я бы предложил что-то типа такого (но я не проверял) + есть проблема в этом предложении, связанная с https://github.com/caenHV/Setup/issues/18
```python
    for ch in channels:
        channel_info = Channel_info.from_db_object(ch["Channel"], ch["Board"])  # type: ignore
        self.__set_parameters(channel_info, {'VSet' : voltage, 'Pw': 1})
```
другой вариант, как кажется, вынести pw_up из цикла

**Comment by AliensWithdrawPeople** [comment]
Твои решения хорошие. Но есть неприятный кейс, когда Pw == 1 и нужно поменять напряжения на каналах. Тогда проблема с неравномерностью подъёма напряжения, вроде, останется. Чтоб от неё избавиться, нужно запись в БД в __set_parameters как-нибудь отпустить (async может быть). Сегодня в виде кода реализую и залью (возможно, даже чекну, так как у меня смена будет ночью).

**Comment by AliensWithdrawPeople** [comment]
**TL;DR**: Вроде, фиксанул в коммите 49b1a9a, но ещё не потестил. Сегодня на дежурстве проведу тесты и отпишусь.

Перебрал __update_parameters -- перекинул BoardCAEN.get_parameters в этот метод (из __set_parameters убрал, чтобы было большее соответствие названию). запись в БД теперь происходит вне __set_parameters после pw_up. Тем самым это не должно приводить к перекосам. Сегодня проверю это.
https://github.com/caenHV/Setup/blob/49b1a9a6932fb9e9a885f15b62375bbf57bd9a2b/caen_setup/Setup/Handler.py#L345-L349

pw_up из цикла вынес. 

> а может было бы ещё интереснее сделать типа
> 
> ```python
> def __set_parameters(self, channels: List[Channel_info], params_dict: List[Tuple[str, float]]) -> bool:
>  ...
> 
> ...
>   channels = list()
>   for ch in channels:
>         channel_info = Channel_info.from_db_object(ch["Channel"], ch["Board"])  # type: ignore
>         channels.append(channel_info)
>   self.__set_parameters(channels, [('VSet': voltage), ('Pw': 1)])
> ```
В свете изменений (вынос __update_parameters из __set_parameters) необходимость channels: List[Channel_info] не так ясна. Хотя учитывая то, что у нас все каналы делятся на слои, разумно везде добавить возможность передачи в метод листа. Подумаю об этом.

**Comment by AliensWithdrawPeople** [comment]
Проверил. Всё работает быстрее, вроде. Осталось только поменять RUp и RDown. Хочу добавить это как параметр в тикета SetVoltage_Ticket с дефолтным значением каким-нибудь (у Попова спрошу завтра конкретное значение).

**Comment by AliensWithdrawPeople** [comment]
RUp и RDown теперь пропорцианальны напряжению. Это сделана для того, чтобы сохранялась пропрциональность при подъёме/сбросе напряжения.
