### ISSUE TITLE
Parameters in set_parameters (possible enhancement)

### ISSUE THREAD

**Issue by nikita-p** [caenHV/Setup#18]
*Предложение*: использовать в `set_parameters` (в boardcaen, и в fakeboard тогда) вместо `Dict` `OrderedDict` (или `List[Tuple[str, float]]`)

https://github.com/caenHV/Setup/blob/26b9f58bcf71bccab48e6b478551fc977ff21e65/caen_setup/Setup/boardcaen.py#L56-L58

*Обоснование*: dict не обязан держать порядок элементов, т.е. сейчас параметры на каен будут ставиться в принципе в произвольном порядке, но например в случае, когда мы хотим передать такой словарь параметров как например `{'VSet': 100, 'Pw': 1}` порядок важен, поскольку если сначала выставить Pw, то напряжение может скакнуть до мусора, записанного в VSet ранее

**Comment by AliensWithdrawPeople** [comment]
Перешёл к List[Tuple[str, float]] в коммитах 66f90b6 и 49b1a9a. Возможно, не везде исправил. Чекну и, если всё ок, закрою.
